<?php 
/**
 * Implements hook_theme().
 */
 
function drupalbook_theme($existing, $type, $theme, $path)
{
    return array('new_list' => array('variables' => array('items' => array(), 'title' => '')));
}

/**
 * Used for altering save button in comments
 */

function drupalbook_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if($form_id == 'comment_comment_form')
    {
        $form['actions']['submit']['#value'] = t('comment');
    }
}